import Foundation

@_spi(Internal) public enum BlendMode: String, MappedEnum {
  case passThrough = "PassThrough"
  case normal = "Normal"
  case darken = "Darken"
  case multiply = "Multiply"
  case colorBurn = "ColorBurn"
  case linearBurn = "LinearBurn"
  case lighten = "Lighten"
  case screen = "Screen"
  case colorDodge = "ColorDodge"
  case linearDodge = "LinearDodge"
  case lightenColor = "LightenColor"
  case darkenColor = "DarkenColor"
  case overlay = "Overlay"
  case softLight = "SoftLight"
  case hardLight = "HardLight"
  case vividLight = "VividLight"
  case linearLight = "LinearLight"
  case pinLight = "PinLight"
  case hardMix = "HardMix"
  case difference = "Difference"
  case exclusion = "Exclusion"
  case subtract = "Subtract"
  case divide = "Divide"
  case hue = "Hue"
  case saturation = "Saturation"
  case color = "Color"
  case luminosity = "Luminosity"

  @_spi(Internal) public var description: String {
    switch self {
    case .passThrough: "Pass Through"
    case .normal: "Normal"
    case .darken: "Darken"
    case .multiply: "Multiply"
    case .colorBurn: "Color Burn"
    case .linearBurn: "Linear Burn"
    case .darkenColor: "Darken Color"
    case .lighten: "Lighten"
    case .screen: "Screen"
    case .colorDodge: "Color Dodge"
    case .linearDodge: "Linear Dodge"
    case .lightenColor: "Lighten Color"
    case .overlay: "Overlay"
    case .softLight: "Soft Light"
    case .hardLight: "Hard Light"
    case .vividLight: "Vivid Light"
    case .linearLight: "Linear Light"
    case .pinLight: "Pin Light"
    case .hardMix: "Hard Mix"
    case .difference: "Difference"
    case .exclusion: "Exclusion"
    case .subtract: "Subtract"
    case .divide: "Divide"
    case .hue: "Hue"
    case .saturation: "Saturation"
    case .color: "Color"
    case .luminosity: "Luminosity"
    }
  }

  @_spi(Internal) public var imageName: String? { nil }
}
