import Foundation

@_spi(Internal) public enum BlendMode: String, MappedEnum, Labelable {
  case passThrough = "PassThrough"
  case normal = "Normal"
  case darken = "Darken"
  case multiply = "Multiply"
  case colorBurn = "ColorBurn"
  case linearBurn = "LinearBurn"
  case lighten = "Lighten"
  case screen = "Screen"
  case colorDodge = "ColorDodge"
  case linearDodge = "LinearDodge"
  case lightenColor = "LightenColor"
  case darkenColor = "DarkenColor"
  case overlay = "Overlay"
  case softLight = "SoftLight"
  case hardLight = "HardLight"
  case vividLight = "VividLight"
  case linearLight = "LinearLight"
  case pinLight = "PinLight"
  case hardMix = "HardMix"
  case difference = "Difference"
  case exclusion = "Exclusion"
  case subtract = "Subtract"
  case divide = "Divide"
  case hue = "Hue"
  case saturation = "Saturation"
  case color = "Color"
  case luminosity = "Luminosity"

  @_spi(Internal) public var localizationValue: String.LocalizationValue {
    switch self {
    case .passThrough: "ly_img_editor_sheet_layer_blend_mode_option_pass_through"
    case .normal: "ly_img_editor_sheet_layer_blend_mode_option_normal"
    case .darken: "ly_img_editor_sheet_layer_blend_mode_option_darken"
    case .multiply: "ly_img_editor_sheet_layer_blend_mode_option_multiply"
    case .colorBurn: "ly_img_editor_sheet_layer_blend_mode_option_color_burn"
    case .linearBurn: "ly_img_editor_sheet_layer_blend_mode_option_linear_burn"
    case .darkenColor: "ly_img_editor_sheet_layer_blend_mode_option_darken_color"
    case .lighten: "ly_img_editor_sheet_layer_blend_mode_option_lighten"
    case .screen: "ly_img_editor_sheet_layer_blend_mode_option_screen"
    case .colorDodge: "ly_img_editor_sheet_layer_blend_mode_option_color_dodge"
    case .linearDodge: "ly_img_editor_sheet_layer_blend_mode_option_linear_dodge"
    case .lightenColor: "ly_img_editor_sheet_layer_blend_mode_option_lighten_color"
    case .overlay: "ly_img_editor_sheet_layer_blend_mode_option_overlay"
    case .softLight: "ly_img_editor_sheet_layer_blend_mode_option_soft_light"
    case .hardLight: "ly_img_editor_sheet_layer_blend_mode_option_hard_light"
    case .vividLight: "ly_img_editor_sheet_layer_blend_mode_option_vivid_light"
    case .linearLight: "ly_img_editor_sheet_layer_blend_mode_option_linear_light"
    case .pinLight: "ly_img_editor_sheet_layer_blend_mode_option_pin_light"
    case .hardMix: "ly_img_editor_sheet_layer_blend_mode_option_hard_mix"
    case .difference: "ly_img_editor_sheet_layer_blend_mode_option_difference"
    case .exclusion: "ly_img_editor_sheet_layer_blend_mode_option_exclusion"
    case .subtract: "ly_img_editor_sheet_layer_blend_mode_option_subtract"
    case .divide: "ly_img_editor_sheet_layer_blend_mode_option_divide"
    case .hue: "ly_img_editor_sheet_layer_blend_mode_option_hue"
    case .saturation: "ly_img_editor_sheet_layer_blend_mode_option_saturation"
    case .color: "ly_img_editor_sheet_layer_blend_mode_option_color"
    case .luminosity: "ly_img_editor_sheet_layer_blend_mode_option_luminosity"
    }
  }

  @_spi(Internal) public var imageName: String? { nil }
}
